# AdvancedPlayTime Configuration

# GUI Settings
gui:
  title: "&#59a87b&lᴛᴏᴘ ᴘʟᴀʏᴛɪᴍᴇ ᴘʟᴀʏᴇʀꜱ"
  size: 27
  update-interval: 60 # Update interval in seconds
  fill-empty: true
  fill-material: "BLACK_STAINED_GLASS_PANE"
  
  # Event Info Book
  event-info:
    name: "&6&lᴡᴇᴇᴋʟʏ ᴘʟᴀʏᴛɪᴍᴇ ᴇᴠᴇɴᴛ"
    material: "PLAYER_HEAD"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTcwMjE2YmFmMWI5Njc1ZjgwNWRmZGY5NWRiMDQzYWZlNmY4ODFjODJiMjU5MzdlNDZiMTUwNjhlOGYzZTg4MiJ9fX0="
    lore:
      - '&7ᴡᴇᴇᴋʟʏ ᴘʟᴀʏ ᴛɪᴍᴇ ʀᴇᴡᴀʀᴅ'
      - '&7ᴛʜᴇ ꜰɪʀꜱᴛ 5 ᴘʟᴀʏᴇʀꜱ ᴡʜᴏ ꜱᴘᴇɴᴅ'
      - '&7ᴛʜᴇ ᴍᴏꜱᴛ ᴛɪᴍᴇ ɪɴ ᴛʜᴇ ɢᴀᴍᴇ'
      - '&7ᴡɪʟʟ ᴡɪɴ ᴘʀɪᴢᴇꜱ.'
      - '&bʀᴀɴᴋɪɴɢ ʀᴇꜱᴇᴛꜱ ᴇᴠᴇʀʏ ᴡᴇᴇᴋ'
      - ''
      - '&6ᴘʀɪᴢᴇꜱ:'
      - '&71. &e500.000$ &7+ &b1x ᴍᴏɴᴇʏ ᴄᴀꜱᴇ'
      - '&72. &e250.000$'
      - '&73. &e100.000$'
      - '&74. &e75.000$'
      - '&75. &e50.000$'

  # Update Timer Clock
  update-timer:
    name: "&6ᴜᴘᴅᴀᴛᴇ ɪɴꜰᴏ"
    material: "PLAYER_HEAD"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWE2YTk2YWE4N2ViM2EwZmJmMWE2ZjBmMDQxZWZhZmVmOWIzMGM5MzdjYmZlY2NkYjVlN2Q1ZDMyYjg3ZjJjNSJ9fX0="
    lore:
      - "&7ɴᴇxᴛ ᴜᴘᴅᴀᴛᴇ: &e%time% seconds"

  # Top Player Slots (Center aligned)
  top-player-slots: [10, 11, 12, 13, 14]
  top-player-format:
    name: "&e#%position%. &7%player%"
    default_texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4ODFlNTUyMmVlZWQxZTNkYWYyMTdhMzhjMWEifX19"
    position_textures:
      "1": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFiYzJiY2ZiMmJkMzc1OWU2YjFlODZmYzdhNzk1ODVlMTEyN2RkMzU3ZmMyMDI4OTNmOWRlMjQxYmM5ZTUzMCJ9fX0="
      "2": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGNkOWVlZWU4ODM0Njg4ODFkODM4NDhhNDZiZjMwMTI0ODVjMjNmNzU3NTNiOGZiZTg0ODczNDE0MTk4NDcifX19="
      "3": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWQ0ZWFlMTM5MzM4NjBhNmRmNWU4ZTk1NTY5M2I5NWE4YzNiMTVjMzZiOGI1ODc1MzJhYzA5OTZiYzM3ZTUifX19="
      "4": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDJlNzhmYjIyNDI0MjMyZGMyN2I4MWZiY2I0N2ZkMjRjMWFjZjc2MDk4NzUzZjJkOWMyODU5ODI4N2RiNSJ9fX0"
      "5": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmQ1N2UzYmM4OGE2NTczMGUzMWExNGUzZjQxZTAzOGE1ZWNmMDg5MWE2YzI0MzY0M2I4ZTU0NzZhZTIifX19="
    lore:
      - "&7Weekly Time: &e%weekly_time%"

  # Custom Items
  custom-items:
    weekly-stats:
      enabled: true
      slot: 18
      material: "PLAYER_HEAD"
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODg2MTc3ZjliNjg5ZDA0YzE0YThmMDU2ZGFlMzNjYmJlZWY5YTBlNmFlM2QwZjVkNjViMzQ4MmY0YmE1OGQ2ZSJ9fX0="
      name: "&6ʏᴏᴜʀ ꜱᴛᴀᴛꜱ"
      lore:
        - "&7ʏᴏᴜʀ ʀᴀɴᴋ: &e#%position%"
        - "&7ᴡᴇᴇᴋʟʏ ᴛɪᴍᴇ: &e%weekly_time%"
        - "&7ᴛᴏᴛᴀʟ ᴛɪᴍᴇ: &e%total_time%"

# Messages
messages:
  prefix: "&eᴘʟᴀʏᴛɪᴍᴇ &7» "
  reload: "&aConfiguration reloaded successfully!"
  reset: "&aWeekly playtime has been reset!"
  no-permission: "&cYou don't have permission to use this command!"

# Weekly Reset Settings
weekly-reset:
  day: 1 # 1 = Monday, 7 = Sunday
  hour: 0 # 0-23
  minute: 0 # 0-59

# Rewards Settings
rewards:
  enabled: true
  broadcast:
    enabled: true
    title:
      enabled: true
      text: "&e&lWeekly Rewards"
      subtitle: "&7Top 5 players have been rewarded!"
      fade-in: 10
      stay: 70
      fade-out: 20
    chat:
      enabled: true
      format:
        - "&8&m                                                &r"
        - "&e&lWeekly Playtime Rewards"
        - "&71. &e%player_1% &8- &e%time_1%"
        - "&72. &e%player_2% &8- &e%time_2%"
        - "&73. &e%player_3% &8- &e%time_3%"
        - "&74. &e%player_4% &8- &e%time_4%"
        - "&75. &e%player_5% &8- &e%time_5%"
        - "&8&m                                                &r"
  commands:
    1:
      - "eco give %player% 10000"
    2:
      - "eco give %player% 7500"
    3:
      - "eco give %player% 5000"
    4:
      - "eco give %player% 2500"
    5:
      - "eco give %player% 1000"

# Storage Settings
storage:
  save-interval: 5 # Auto-save interval in minutes

# AFK Settings
afk:
  enabled: true
  timeout: 1 # Time in seconds before a player is marked as AFK
  stop-counting:
    session: false
    weekly: true
    total: true
  protection:
    prevent-teleport: true
    prevent-damage: true
    prevent-chat: true
    messages:
      teleport: "&cYou cannot teleport to an AFK player!"
      damage: "&cYou cannot damage an AFK player!"
  hologram:
    enabled: true
    height: 2.5
    animation:
      interval: 20 # Tick cinsinden animasyon hızı (20 tick = 1 saniye)
      frames:
        - "&7zZz.."
        - "&7zzZz..."
        - "&7zZz.."
        - "&7zzZz..."
  bossbar:
    enabled: true
    title: "&cYou are currently AFK"
    color: RED
    style: SOLID

 
